services:
  patient-service:
    build:
      context: ./patient-service
      dockerfile: Dockerfile-service
    container_name: patient-service
    image: local/patient-service:dev
    networks:
      - patient_service_db_network
      - patient_service_grpc_network
    ports:
      - "4001:4001"
    depends_on:
      patient-db:
        condition: service_healthy
      billing-service:
        condition: service_started
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://patient-db:3306/patient_db
      - SPRING_DATASOURCE_USERNAME=patient_service_user
      - SPRING_DATASOURCE_PASSWORD=patient_service_password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_SQL_INIT_MODE=always
      - BILLING_SERVICE_ADDRESS=billing-service
      - BILLING_SERVICE_GRPC_PORT=9001

  billing-service:
    build:
      context: ./billing-service
      dockerfile: Dockerfile-service
    container_name: billing-service
    image: local/billing-service:dev
    ports:
      - "4002:4002"
      - "9001:9001"
    networks:
      - patient_service_grpc_network
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  patient-db:
    build:
      context: ./patient-service
      dockerfile: Dockerfile-db
    container_name: patient-db
    image: local/patient-db:dev
    networks:
      - patient_service_db_network
    ports:
      - "3001:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./db-data/patient-db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=patient_db
      - MYSQL_USER=patient_service_user
      - MYSQL_PASSWORD=patient_service_password

networks:
  patient_service_db_network:
    driver: bridge
#    internal: true
  patient_service_grpc_network:
    driver: bridge

volumes:
  patient-db-data: