FROM gradle:9.2.1-jdk25 AS build-cache
WORKDIR /app
COPY build.gradle settings.gradle gradle ./
RUN gradle buildDependencies --offline --no-daemon || true


FROM gradle:9.2.1-jdk25 AS builder
COPY --from=build-cache /root/.gradle /root/.gradle
WORKDIR /app
COPY build.gradle .
COPY settings.gradle .
COPY src ./src
RUN gradle bootJar --no-daemon

FROM eclipse-temurin:25-jre-alpine AS runner
WORKDIR /app
COPY --from=builder /app/build/libs/billing-service-1.0-SNAPSHOT.jar ./app.jar
EXPOSE 4002
EXPOSE 9001
ENTRYPOINT ["java", "-jar", "app.jar"]


